// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gosaga

import (
	"context"

	"github.com/Filin153/gosaga"
	"github.com/Filin153/gosaga/domain"
	"github.com/Filin153/gosaga/storage/database"
	mock "github.com/stretchr/testify/mock"
)

// newMockgosagaWorkerInterface creates a new instance of mockgosagaWorkerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgosagaWorkerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgosagaWorkerInterface {
	mock := &mockgosagaWorkerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgosagaWorkerInterface is an autogenerated mock type for the gosagaWorkerInterface type
type mockgosagaWorkerInterface struct {
	mock.Mock
}

type mockgosagaWorkerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgosagaWorkerInterface) EXPECT() *mockgosagaWorkerInterface_Expecter {
	return &mockgosagaWorkerInterface_Expecter{mock: &_m.Mock}
}

// DlqWorker provides a mock function for the type mockgosagaWorkerInterface
func (_mock *mockgosagaWorkerInterface) DlqWorker(task *domain.SagaTask, sess database.Session) error {
	ret := _mock.Called(task, sess)

	if len(ret) == 0 {
		panic("no return value specified for DlqWorker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.SagaTask, database.Session) error); ok {
		r0 = returnFunc(task, sess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockgosagaWorkerInterface_DlqWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DlqWorker'
type mockgosagaWorkerInterface_DlqWorker_Call struct {
	*mock.Call
}

// DlqWorker is a helper method to define mock.On call
//   - task *domain.SagaTask
//   - sess database.Session
func (_e *mockgosagaWorkerInterface_Expecter) DlqWorker(task interface{}, sess interface{}) *mockgosagaWorkerInterface_DlqWorker_Call {
	return &mockgosagaWorkerInterface_DlqWorker_Call{Call: _e.mock.On("DlqWorker", task, sess)}
}

func (_c *mockgosagaWorkerInterface_DlqWorker_Call) Run(run func(task *domain.SagaTask, sess database.Session)) *mockgosagaWorkerInterface_DlqWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.SagaTask
		if args[0] != nil {
			arg0 = args[0].(*domain.SagaTask)
		}
		var arg1 database.Session
		if args[1] != nil {
			arg1 = args[1].(database.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockgosagaWorkerInterface_DlqWorker_Call) Return(err error) *mockgosagaWorkerInterface_DlqWorker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockgosagaWorkerInterface_DlqWorker_Call) RunAndReturn(run func(task *domain.SagaTask, sess database.Session) error) *mockgosagaWorkerInterface_DlqWorker_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type mockgosagaWorkerInterface
func (_mock *mockgosagaWorkerInterface) New(ctx context.Context) (gosaga.gosagaWorkerInterface, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 gosaga.gosagaWorkerInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (gosaga.gosagaWorkerInterface, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) gosaga.gosagaWorkerInterface); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gosaga.gosagaWorkerInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgosagaWorkerInterface_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type mockgosagaWorkerInterface_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockgosagaWorkerInterface_Expecter) New(ctx interface{}) *mockgosagaWorkerInterface_New_Call {
	return &mockgosagaWorkerInterface_New_Call{Call: _e.mock.On("New", ctx)}
}

func (_c *mockgosagaWorkerInterface_New_Call) Run(run func(ctx context.Context)) *mockgosagaWorkerInterface_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockgosagaWorkerInterface_New_Call) Return(gosagaWorkerInterfaceMoqParam gosaga.gosagaWorkerInterface, err error) *mockgosagaWorkerInterface_New_Call {
	_c.Call.Return(gosagaWorkerInterfaceMoqParam, err)
	return _c
}

func (_c *mockgosagaWorkerInterface_New_Call) RunAndReturn(run func(ctx context.Context) (gosaga.gosagaWorkerInterface, error)) *mockgosagaWorkerInterface_New_Call {
	_c.Call.Return(run)
	return _c
}

// Worker provides a mock function for the type mockgosagaWorkerInterface
func (_mock *mockgosagaWorkerInterface) Worker(task *domain.SagaTask, sess database.Session) error {
	ret := _mock.Called(task, sess)

	if len(ret) == 0 {
		panic("no return value specified for Worker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.SagaTask, database.Session) error); ok {
		r0 = returnFunc(task, sess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockgosagaWorkerInterface_Worker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Worker'
type mockgosagaWorkerInterface_Worker_Call struct {
	*mock.Call
}

// Worker is a helper method to define mock.On call
//   - task *domain.SagaTask
//   - sess database.Session
func (_e *mockgosagaWorkerInterface_Expecter) Worker(task interface{}, sess interface{}) *mockgosagaWorkerInterface_Worker_Call {
	return &mockgosagaWorkerInterface_Worker_Call{Call: _e.mock.On("Worker", task, sess)}
}

func (_c *mockgosagaWorkerInterface_Worker_Call) Run(run func(task *domain.SagaTask, sess database.Session)) *mockgosagaWorkerInterface_Worker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.SagaTask
		if args[0] != nil {
			arg0 = args[0].(*domain.SagaTask)
		}
		var arg1 database.Session
		if args[1] != nil {
			arg1 = args[1].(database.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockgosagaWorkerInterface_Worker_Call) Return(err error) *mockgosagaWorkerInterface_Worker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockgosagaWorkerInterface_Worker_Call) RunAndReturn(run func(task *domain.SagaTask, sess database.Session) error) *mockgosagaWorkerInterface_Worker_Call {
	_c.Call.Return(run)
	return _c
}
