version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none

  enable:
    - govet # базовые проверки Go
    - staticcheck # "умный" анализ
    - unused # неиспользуемые переменные/функции/типы
    - ineffassign # присваивания без использования
    - errcheck # пропущенные проверки ошибок
