packages:
  github.com/Filin153/gosaga:
    config:
      all: true
      dir: mocks/core

  github.com/Filin153/gosaga/storage/broker/kafka:
    config:
      all: true
      dir: mocks/kafka

  github.com/Filin153/gosaga/storage/database:
    config:
      all: true
      dir: mocks/database
