// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka

import (
	"context"

	"github.com/Filin153/gosaga/domain"
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockWriter
func (_mock *MockWriter) Write(ctx context.Context, msg *domain.SagaMsg, rollback *domain.SagaMsg, idempotencyKey string) error {
	ret := _mock.Called(ctx, msg, rollback, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SagaMsg, *domain.SagaMsg, string) error); ok {
		r0 = returnFunc(ctx, msg, rollback, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *domain.SagaMsg
//   - rollback *domain.SagaMsg
//   - idempotencyKey string
func (_e *MockWriter_Expecter) Write(ctx interface{}, msg interface{}, rollback interface{}, idempotencyKey interface{}) *MockWriter_Write_Call {
	return &MockWriter_Write_Call{Call: _e.mock.On("Write", ctx, msg, rollback, idempotencyKey)}
}

func (_c *MockWriter_Write_Call) Run(run func(ctx context.Context, msg *domain.SagaMsg, rollback *domain.SagaMsg, idempotencyKey string)) *MockWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SagaMsg
		if args[1] != nil {
			arg1 = args[1].(*domain.SagaMsg)
		}
		var arg2 *domain.SagaMsg
		if args[2] != nil {
			arg2 = args[2].(*domain.SagaMsg)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWriter_Write_Call) Return(err error) *MockWriter_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_Write_Call) RunAndReturn(run func(ctx context.Context, msg *domain.SagaMsg, rollback *domain.SagaMsg, idempotencyKey string) error) *MockWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockReader
func (_mock *MockReader) Read() <-chan *sarama.ConsumerMessage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 <-chan *sarama.ConsumerMessage
	if returnFunc, ok := ret.Get(0).(func() <-chan *sarama.ConsumerMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *sarama.ConsumerMessage)
		}
	}
	return r0
}

// MockReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockReader_Expecter) Read() *MockReader_Read_Call {
	return &MockReader_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockReader_Read_Call) Run(run func()) *MockReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReader_Read_Call) Return(consumerMessageCh <-chan *sarama.ConsumerMessage) *MockReader_Read_Call {
	_c.Call.Return(consumerMessageCh)
	return _c
}

func (_c *MockReader_Read_Call) RunAndReturn(run func() <-chan *sarama.ConsumerMessage) *MockReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockReader
func (_mock *MockReader) Run(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockReader_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockReader_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReader_Expecter) Run(ctx interface{}) *MockReader_Run_Call {
	return &MockReader_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockReader_Run_Call) Run(run func(ctx context.Context)) *MockReader_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Run_Call) Return() *MockReader_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReader_Run_Call) RunAndReturn(run func(ctx context.Context)) *MockReader_Run_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockReader
func (_mock *MockReader) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReader_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockReader_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockReader_Expecter) Shutdown() *MockReader_Shutdown_Call {
	return &MockReader_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockReader_Shutdown_Call) Run(run func()) *MockReader_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReader_Shutdown_Call) Return(err error) *MockReader_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReader_Shutdown_Call) RunAndReturn(run func() error) *MockReader_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
