// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gosaga

import (
	"context"

	"github.com/Filin153/gosaga/domain"
	"github.com/Filin153/gosaga/storage/database"
	"github.com/Filin153/gosaga/v1"
	"github.com/IBM/sarama"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Create(ctx context.Context, task *domain.SagaTask) (int64, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SagaTask) (int64, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SagaTask) int64); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.SagaTask) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.SagaTask
func (_e *MockTaskRepository_Expecter) Create(ctx interface{}, task interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, task *domain.SagaTask)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SagaTask
		if args[1] != nil {
			arg1 = args[1].(*domain.SagaTask)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(n int64, err error) *MockTaskRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(ctx context.Context, task *domain.SagaTask) (int64, error)) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTaskRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskRepository_Delete_Call {
	return &MockTaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockTaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Delete_Call) Return(err error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByID(ctx context.Context, id int64) (*domain.SagaTask, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.SagaTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.SagaTask, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.SagaTask); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SagaTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockTaskRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTaskRepository_GetByID_Call {
	return &MockTaskRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTaskRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockTaskRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) Return(sagaTask *domain.SagaTask, err error) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(sagaTask, err)
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.SagaTask, error)) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdempotencyKey provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByIdempotencyKey(ctx context.Context, key string) (*domain.SagaTask, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 *domain.SagaTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.SagaTask, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.SagaTask); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SagaTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdempotencyKey'
type MockTaskRepository_GetByIdempotencyKey_Call struct {
	*mock.Call
}

// GetByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockTaskRepository_Expecter) GetByIdempotencyKey(ctx interface{}, key interface{}) *MockTaskRepository_GetByIdempotencyKey_Call {
	return &MockTaskRepository_GetByIdempotencyKey_Call{Call: _e.mock.On("GetByIdempotencyKey", ctx, key)}
}

func (_c *MockTaskRepository_GetByIdempotencyKey_Call) Run(run func(ctx context.Context, key string)) *MockTaskRepository_GetByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetByIdempotencyKey_Call) Return(sagaTask *domain.SagaTask, err error) *MockTaskRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(sagaTask, err)
	return _c
}

func (_c *MockTaskRepository_GetByIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, key string) (*domain.SagaTask, error)) *MockTaskRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStatus provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByStatus(ctx context.Context, status domain.TaskStatus) ([]domain.SagaTask, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatus")
	}

	var r0 []domain.SagaTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskStatus) ([]domain.SagaTask, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskStatus) []domain.SagaTask); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SagaTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TaskStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStatus'
type MockTaskRepository_GetByStatus_Call struct {
	*mock.Call
}

// GetByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status domain.TaskStatus
func (_e *MockTaskRepository_Expecter) GetByStatus(ctx interface{}, status interface{}) *MockTaskRepository_GetByStatus_Call {
	return &MockTaskRepository_GetByStatus_Call{Call: _e.mock.On("GetByStatus", ctx, status)}
}

func (_c *MockTaskRepository_GetByStatus_Call) Run(run func(ctx context.Context, status domain.TaskStatus)) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TaskStatus
		if args[1] != nil {
			arg1 = args[1].(domain.TaskStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetByStatus_Call) Return(sagaTasks []domain.SagaTask, err error) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Return(sagaTasks, err)
	return _c
}

func (_c *MockTaskRepository_GetByStatus_Call) RunAndReturn(run func(ctx context.Context, status domain.TaskStatus) ([]domain.SagaTask, error)) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Update(ctx context.Context, task *domain.SagaTask) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SagaTask) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.SagaTask
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, task interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, task *domain.SagaTask)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SagaTask
		if args[1] != nil {
			arg1 = args[1].(*domain.SagaTask)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(err error) *MockTaskRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(ctx context.Context, task *domain.SagaTask) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) UpdateByID(ctx context.Context, id int64, update domain.SagaTaskUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.SagaTaskUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockTaskRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - update domain.SagaTaskUpdate
func (_e *MockTaskRepository_Expecter) UpdateByID(ctx interface{}, id interface{}, update interface{}) *MockTaskRepository_UpdateByID_Call {
	return &MockTaskRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, update)}
}

func (_c *MockTaskRepository_UpdateByID_Call) Run(run func(ctx context.Context, id int64, update domain.SagaTaskUpdate)) *MockTaskRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 domain.SagaTaskUpdate
		if args[2] != nil {
			arg2 = args[2].(domain.SagaTaskUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskRepository_UpdateByID_Call) Return(err error) *MockTaskRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id int64, update domain.SagaTaskUpdate) error) *MockTaskRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// WithSession provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) WithSession(sess database.Session) database.TaskRepository {
	ret := _mock.Called(sess)

	if len(ret) == 0 {
		panic("no return value specified for WithSession")
	}

	var r0 database.TaskRepository
	if returnFunc, ok := ret.Get(0).(func(database.Session) database.TaskRepository); ok {
		r0 = returnFunc(sess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.TaskRepository)
		}
	}
	return r0
}

// MockTaskRepository_WithSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithSession'
type MockTaskRepository_WithSession_Call struct {
	*mock.Call
}

// WithSession is a helper method to define mock.On call
//   - sess database.Session
func (_e *MockTaskRepository_Expecter) WithSession(sess interface{}) *MockTaskRepository_WithSession_Call {
	return &MockTaskRepository_WithSession_Call{Call: _e.mock.On("WithSession", sess)}
}

func (_c *MockTaskRepository_WithSession_Call) Run(run func(sess database.Session)) *MockTaskRepository_WithSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Session
		if args[0] != nil {
			arg0 = args[0].(database.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_WithSession_Call) Return(taskRepository database.TaskRepository) *MockTaskRepository_WithSession_Call {
	_c.Call.Return(taskRepository)
	return _c
}

func (_c *MockTaskRepository_WithSession_Call) RunAndReturn(run func(sess database.Session) database.TaskRepository) *MockTaskRepository_WithSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDLQRepository creates a new instance of MockDLQRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDLQRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDLQRepository {
	mock := &MockDLQRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDLQRepository is an autogenerated mock type for the DLQRepository type
type MockDLQRepository struct {
	mock.Mock
}

type MockDLQRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDLQRepository) EXPECT() *MockDLQRepository_Expecter {
	return &MockDLQRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) Create(ctx context.Context, task *domain.DLQTask) (int64, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DLQTask) (int64, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DLQTask) int64); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.DLQTask) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDLQRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.DLQTask
func (_e *MockDLQRepository_Expecter) Create(ctx interface{}, task interface{}) *MockDLQRepository_Create_Call {
	return &MockDLQRepository_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockDLQRepository_Create_Call) Run(run func(ctx context.Context, task *domain.DLQTask)) *MockDLQRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.DLQTask
		if args[1] != nil {
			arg1 = args[1].(*domain.DLQTask)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDLQRepository_Create_Call) Return(n int64, err error) *MockDLQRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDLQRepository_Create_Call) RunAndReturn(run func(ctx context.Context, task *domain.DLQTask) (int64, error)) *MockDLQRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDLQRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDLQRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockDLQRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockDLQRepository_Delete_Call {
	return &MockDLQRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDLQRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockDLQRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDLQRepository_Delete_Call) Return(err error) *MockDLQRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDLQRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockDLQRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) GetByID(ctx context.Context, id int64) (*domain.DLQTask, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.DLQTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.DLQTask, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.DLQTask); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DLQTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDLQRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockDLQRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockDLQRepository_GetByID_Call {
	return &MockDLQRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDLQRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockDLQRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDLQRepository_GetByID_Call) Return(dLQTask *domain.DLQTask, err error) *MockDLQRepository_GetByID_Call {
	_c.Call.Return(dLQTask, err)
	return _c
}

func (_c *MockDLQRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.DLQTask, error)) *MockDLQRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStatus provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) GetByStatus(ctx context.Context, status domain.TaskStatus) ([]domain.DLQEntry, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatus")
	}

	var r0 []domain.DLQEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskStatus) ([]domain.DLQEntry, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskStatus) []domain.DLQEntry); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DLQEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TaskStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_GetByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStatus'
type MockDLQRepository_GetByStatus_Call struct {
	*mock.Call
}

// GetByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status domain.TaskStatus
func (_e *MockDLQRepository_Expecter) GetByStatus(ctx interface{}, status interface{}) *MockDLQRepository_GetByStatus_Call {
	return &MockDLQRepository_GetByStatus_Call{Call: _e.mock.On("GetByStatus", ctx, status)}
}

func (_c *MockDLQRepository_GetByStatus_Call) Run(run func(ctx context.Context, status domain.TaskStatus)) *MockDLQRepository_GetByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TaskStatus
		if args[1] != nil {
			arg1 = args[1].(domain.TaskStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDLQRepository_GetByStatus_Call) Return(dLQEntrys []domain.DLQEntry, err error) *MockDLQRepository_GetByStatus_Call {
	_c.Call.Return(dLQEntrys, err)
	return _c
}

func (_c *MockDLQRepository_GetByStatus_Call) RunAndReturn(run func(ctx context.Context, status domain.TaskStatus) ([]domain.DLQEntry, error)) *MockDLQRepository_GetByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTaskID provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) GetByTaskID(ctx context.Context, taskID int64) (*domain.DLQTask, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTaskID")
	}

	var r0 *domain.DLQTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.DLQTask, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.DLQTask); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DLQTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_GetByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTaskID'
type MockDLQRepository_GetByTaskID_Call struct {
	*mock.Call
}

// GetByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
func (_e *MockDLQRepository_Expecter) GetByTaskID(ctx interface{}, taskID interface{}) *MockDLQRepository_GetByTaskID_Call {
	return &MockDLQRepository_GetByTaskID_Call{Call: _e.mock.On("GetByTaskID", ctx, taskID)}
}

func (_c *MockDLQRepository_GetByTaskID_Call) Run(run func(ctx context.Context, taskID int64)) *MockDLQRepository_GetByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDLQRepository_GetByTaskID_Call) Return(dLQTask *domain.DLQTask, err error) *MockDLQRepository_GetByTaskID_Call {
	_c.Call.Return(dLQTask, err)
	return _c
}

func (_c *MockDLQRepository_GetByTaskID_Call) RunAndReturn(run func(ctx context.Context, taskID int64) (*domain.DLQTask, error)) *MockDLQRepository_GetByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// GetErrorsWithAttempts provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) GetErrorsWithAttempts(ctx context.Context) ([]domain.DLQEntry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetErrorsWithAttempts")
	}

	var r0 []domain.DLQEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.DLQEntry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.DLQEntry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DLQEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_GetErrorsWithAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetErrorsWithAttempts'
type MockDLQRepository_GetErrorsWithAttempts_Call struct {
	*mock.Call
}

// GetErrorsWithAttempts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDLQRepository_Expecter) GetErrorsWithAttempts(ctx interface{}) *MockDLQRepository_GetErrorsWithAttempts_Call {
	return &MockDLQRepository_GetErrorsWithAttempts_Call{Call: _e.mock.On("GetErrorsWithAttempts", ctx)}
}

func (_c *MockDLQRepository_GetErrorsWithAttempts_Call) Run(run func(ctx context.Context)) *MockDLQRepository_GetErrorsWithAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_GetErrorsWithAttempts_Call) Return(dLQEntrys []domain.DLQEntry, err error) *MockDLQRepository_GetErrorsWithAttempts_Call {
	_c.Call.Return(dLQEntrys, err)
	return _c
}

func (_c *MockDLQRepository_GetErrorsWithAttempts_Call) RunAndReturn(run func(ctx context.Context) ([]domain.DLQEntry, error)) *MockDLQRepository_GetErrorsWithAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) Update(ctx context.Context, task *domain.DLQTask) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DLQTask) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDLQRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDLQRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.DLQTask
func (_e *MockDLQRepository_Expecter) Update(ctx interface{}, task interface{}) *MockDLQRepository_Update_Call {
	return &MockDLQRepository_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *MockDLQRepository_Update_Call) Run(run func(ctx context.Context, task *domain.DLQTask)) *MockDLQRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.DLQTask
		if args[1] != nil {
			arg1 = args[1].(*domain.DLQTask)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDLQRepository_Update_Call) Return(err error) *MockDLQRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDLQRepository_Update_Call) RunAndReturn(run func(ctx context.Context, task *domain.DLQTask) error) *MockDLQRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) UpdateByID(ctx context.Context, id int64, update domain.DLQTaskUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.DLQTaskUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDLQRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockDLQRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - update domain.DLQTaskUpdate
func (_e *MockDLQRepository_Expecter) UpdateByID(ctx interface{}, id interface{}, update interface{}) *MockDLQRepository_UpdateByID_Call {
	return &MockDLQRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, update)}
}

func (_c *MockDLQRepository_UpdateByID_Call) Run(run func(ctx context.Context, id int64, update domain.DLQTaskUpdate)) *MockDLQRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 domain.DLQTaskUpdate
		if args[2] != nil {
			arg2 = args[2].(domain.DLQTaskUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDLQRepository_UpdateByID_Call) Return(err error) *MockDLQRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDLQRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id int64, update domain.DLQTaskUpdate) error) *MockDLQRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// WithSession provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) WithSession(sess database.Session) database.DLQRepository {
	ret := _mock.Called(sess)

	if len(ret) == 0 {
		panic("no return value specified for WithSession")
	}

	var r0 database.DLQRepository
	if returnFunc, ok := ret.Get(0).(func(database.Session) database.DLQRepository); ok {
		r0 = returnFunc(sess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.DLQRepository)
		}
	}
	return r0
}

// MockDLQRepository_WithSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithSession'
type MockDLQRepository_WithSession_Call struct {
	*mock.Call
}

// WithSession is a helper method to define mock.On call
//   - sess database.Session
func (_e *MockDLQRepository_Expecter) WithSession(sess interface{}) *MockDLQRepository_WithSession_Call {
	return &MockDLQRepository_WithSession_Call{Call: _e.mock.On("WithSession", sess)}
}

func (_c *MockDLQRepository_WithSession_Call) Run(run func(sess database.Session)) *MockDLQRepository_WithSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Session
		if args[0] != nil {
			arg0 = args[0].(database.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_WithSession_Call) Return(dLQRepository database.DLQRepository) *MockDLQRepository_WithSession_Call {
	_c.Call.Return(dLQRepository)
	return _c
}

func (_c *MockDLQRepository_WithSession_Call) RunAndReturn(run func(sess database.Session) database.DLQRepository) *MockDLQRepository_WithSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSession creates a new instance of MockSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSession {
	mock := &MockSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSession is an autogenerated mock type for the Session type
type MockSession struct {
	mock.Mock
}

type MockSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSession) EXPECT() *MockSession_Expecter {
	return &MockSession_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockSession
func (_mock *MockSession) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(arguments) > 0 {
		tmpRet = _mock.Called(ctx, sql, arguments)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, arguments...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSession_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...any
func (_e *MockSession_Expecter) Exec(ctx interface{}, sql interface{}, arguments ...interface{}) *MockSession_Exec_Call {
	return &MockSession_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, arguments...)...)}
}

func (_c *MockSession_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...any)) *MockSession_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSession_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockSession_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockSession_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)) *MockSession_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockSession
func (_mock *MockSession) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockSession_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockSession_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *MockSession_Query_Call {
	return &MockSession_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockSession_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockSession_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSession_Query_Call) Return(rows pgx.Rows, err error) *MockSession_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockSession_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgx.Rows, error)) *MockSession_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockSession
func (_mock *MockSession) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// MockSession_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockSession_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockSession_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *MockSession_QueryRow_Call {
	return &MockSession_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockSession_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockSession_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSession_QueryRow_Call) Return(row pgx.Row) *MockSession_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockSession_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) pgx.Row) *MockSession_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKafkaWriter creates a new instance of MockKafkaWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaWriter {
	mock := &MockKafkaWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKafkaWriter is an autogenerated mock type for the KafkaWriter type
type MockKafkaWriter struct {
	mock.Mock
}

type MockKafkaWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaWriter) EXPECT() *MockKafkaWriter_Expecter {
	return &MockKafkaWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockKafkaWriter
func (_mock *MockKafkaWriter) Write(ctx context.Context, msg *domain.SagaMsg, rollback *domain.SagaMsg, idempotencyKey string) error {
	ret := _mock.Called(ctx, msg, rollback, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SagaMsg, *domain.SagaMsg, string) error); ok {
		r0 = returnFunc(ctx, msg, rollback, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKafkaWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockKafkaWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *domain.SagaMsg
//   - rollback *domain.SagaMsg
//   - idempotencyKey string
func (_e *MockKafkaWriter_Expecter) Write(ctx interface{}, msg interface{}, rollback interface{}, idempotencyKey interface{}) *MockKafkaWriter_Write_Call {
	return &MockKafkaWriter_Write_Call{Call: _e.mock.On("Write", ctx, msg, rollback, idempotencyKey)}
}

func (_c *MockKafkaWriter_Write_Call) Run(run func(ctx context.Context, msg *domain.SagaMsg, rollback *domain.SagaMsg, idempotencyKey string)) *MockKafkaWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SagaMsg
		if args[1] != nil {
			arg1 = args[1].(*domain.SagaMsg)
		}
		var arg2 *domain.SagaMsg
		if args[2] != nil {
			arg2 = args[2].(*domain.SagaMsg)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKafkaWriter_Write_Call) Return(err error) *MockKafkaWriter_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKafkaWriter_Write_Call) RunAndReturn(run func(ctx context.Context, msg *domain.SagaMsg, rollback *domain.SagaMsg, idempotencyKey string) error) *MockKafkaWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKafkaReader creates a new instance of MockKafkaReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaReader {
	mock := &MockKafkaReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKafkaReader is an autogenerated mock type for the KafkaReader type
type MockKafkaReader struct {
	mock.Mock
}

type MockKafkaReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaReader) EXPECT() *MockKafkaReader_Expecter {
	return &MockKafkaReader_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockKafkaReader
func (_mock *MockKafkaReader) Read() <-chan *sarama.ConsumerMessage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 <-chan *sarama.ConsumerMessage
	if returnFunc, ok := ret.Get(0).(func() <-chan *sarama.ConsumerMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *sarama.ConsumerMessage)
		}
	}
	return r0
}

// MockKafkaReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockKafkaReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockKafkaReader_Expecter) Read() *MockKafkaReader_Read_Call {
	return &MockKafkaReader_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockKafkaReader_Read_Call) Run(run func()) *MockKafkaReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKafkaReader_Read_Call) Return(consumerMessageCh <-chan *sarama.ConsumerMessage) *MockKafkaReader_Read_Call {
	_c.Call.Return(consumerMessageCh)
	return _c
}

func (_c *MockKafkaReader_Read_Call) RunAndReturn(run func() <-chan *sarama.ConsumerMessage) *MockKafkaReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockKafkaReader
func (_mock *MockKafkaReader) Run(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockKafkaReader_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockKafkaReader_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKafkaReader_Expecter) Run(ctx interface{}) *MockKafkaReader_Run_Call {
	return &MockKafkaReader_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockKafkaReader_Run_Call) Run(run func(ctx context.Context)) *MockKafkaReader_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKafkaReader_Run_Call) Return() *MockKafkaReader_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockKafkaReader_Run_Call) RunAndReturn(run func(ctx context.Context)) *MockKafkaReader_Run_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockKafkaReader
func (_mock *MockKafkaReader) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKafkaReader_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockKafkaReader_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockKafkaReader_Expecter) Shutdown() *MockKafkaReader_Shutdown_Call {
	return &MockKafkaReader_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockKafkaReader_Shutdown_Call) Run(run func()) *MockKafkaReader_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKafkaReader_Shutdown_Call) Return(err error) *MockKafkaReader_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKafkaReader_Shutdown_Call) RunAndReturn(run func() error) *MockKafkaReader_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkerInterface creates a new instance of MockWorkerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerInterface {
	mock := &MockWorkerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkerInterface is an autogenerated mock type for the WorkerInterface type
type MockWorkerInterface struct {
	mock.Mock
}

type MockWorkerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerInterface) EXPECT() *MockWorkerInterface_Expecter {
	return &MockWorkerInterface_Expecter{mock: &_m.Mock}
}

// DlqWorker provides a mock function for the type MockWorkerInterface
func (_mock *MockWorkerInterface) DlqWorker(ctx context.Context, task *domain.SagaTask, sess database.Session) error {
	ret := _mock.Called(ctx, task, sess)

	if len(ret) == 0 {
		panic("no return value specified for DlqWorker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SagaTask, database.Session) error); ok {
		r0 = returnFunc(ctx, task, sess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkerInterface_DlqWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DlqWorker'
type MockWorkerInterface_DlqWorker_Call struct {
	*mock.Call
}

// DlqWorker is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.SagaTask
//   - sess database.Session
func (_e *MockWorkerInterface_Expecter) DlqWorker(ctx interface{}, task interface{}, sess interface{}) *MockWorkerInterface_DlqWorker_Call {
	return &MockWorkerInterface_DlqWorker_Call{Call: _e.mock.On("DlqWorker", ctx, task, sess)}
}

func (_c *MockWorkerInterface_DlqWorker_Call) Run(run func(ctx context.Context, task *domain.SagaTask, sess database.Session)) *MockWorkerInterface_DlqWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SagaTask
		if args[1] != nil {
			arg1 = args[1].(*domain.SagaTask)
		}
		var arg2 database.Session
		if args[2] != nil {
			arg2 = args[2].(database.Session)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkerInterface_DlqWorker_Call) Return(err error) *MockWorkerInterface_DlqWorker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkerInterface_DlqWorker_Call) RunAndReturn(run func(ctx context.Context, task *domain.SagaTask, sess database.Session) error) *MockWorkerInterface_DlqWorker_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type MockWorkerInterface
func (_mock *MockWorkerInterface) New(ctx context.Context) (gosaga.WorkerInterface, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 gosaga.WorkerInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (gosaga.WorkerInterface, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) gosaga.WorkerInterface); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gosaga.WorkerInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkerInterface_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockWorkerInterface_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWorkerInterface_Expecter) New(ctx interface{}) *MockWorkerInterface_New_Call {
	return &MockWorkerInterface_New_Call{Call: _e.mock.On("New", ctx)}
}

func (_c *MockWorkerInterface_New_Call) Run(run func(ctx context.Context)) *MockWorkerInterface_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkerInterface_New_Call) Return(workerInterface gosaga.WorkerInterface, err error) *MockWorkerInterface_New_Call {
	_c.Call.Return(workerInterface, err)
	return _c
}

func (_c *MockWorkerInterface_New_Call) RunAndReturn(run func(ctx context.Context) (gosaga.WorkerInterface, error)) *MockWorkerInterface_New_Call {
	_c.Call.Return(run)
	return _c
}

// Worker provides a mock function for the type MockWorkerInterface
func (_mock *MockWorkerInterface) Worker(ctx context.Context, task *domain.SagaTask, sess database.Session) error {
	ret := _mock.Called(ctx, task, sess)

	if len(ret) == 0 {
		panic("no return value specified for Worker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SagaTask, database.Session) error); ok {
		r0 = returnFunc(ctx, task, sess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkerInterface_Worker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Worker'
type MockWorkerInterface_Worker_Call struct {
	*mock.Call
}

// Worker is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.SagaTask
//   - sess database.Session
func (_e *MockWorkerInterface_Expecter) Worker(ctx interface{}, task interface{}, sess interface{}) *MockWorkerInterface_Worker_Call {
	return &MockWorkerInterface_Worker_Call{Call: _e.mock.On("Worker", ctx, task, sess)}
}

func (_c *MockWorkerInterface_Worker_Call) Run(run func(ctx context.Context, task *domain.SagaTask, sess database.Session)) *MockWorkerInterface_Worker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SagaTask
		if args[1] != nil {
			arg1 = args[1].(*domain.SagaTask)
		}
		var arg2 database.Session
		if args[2] != nil {
			arg2 = args[2].(database.Session)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkerInterface_Worker_Call) Return(err error) *MockWorkerInterface_Worker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkerInterface_Worker_Call) RunAndReturn(run func(ctx context.Context, task *domain.SagaTask, sess database.Session) error) *MockWorkerInterface_Worker_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktxBeginner creates a new instance of mocktxBeginner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktxBeginner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktxBeginner {
	mock := &mocktxBeginner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktxBeginner is an autogenerated mock type for the txBeginner type
type mocktxBeginner struct {
	mock.Mock
}

type mocktxBeginner_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktxBeginner) EXPECT() *mocktxBeginner_Expecter {
	return &mocktxBeginner_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type mocktxBeginner
func (_mock *mocktxBeginner) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktxBeginner_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type mocktxBeginner_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *mocktxBeginner_Expecter) BeginTx(ctx interface{}, txOptions interface{}) *mocktxBeginner_BeginTx_Call {
	return &mocktxBeginner_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *mocktxBeginner_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *mocktxBeginner_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktxBeginner_BeginTx_Call) Return(tx pgx.Tx, err error) *mocktxBeginner_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *mocktxBeginner_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *mocktxBeginner_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}
