// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gosaga

import (
	"context"

	"github.com/Filin153/gosaga/domain"
	"github.com/Filin153/gosaga/storage/database"
	"github.com/Filin153/gosaga/v1"
	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkerInterface creates a new instance of MockWorkerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerInterface {
	mock := &MockWorkerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkerInterface is an autogenerated mock type for the WorkerInterface type
type MockWorkerInterface struct {
	mock.Mock
}

type MockWorkerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerInterface) EXPECT() *MockWorkerInterface_Expecter {
	return &MockWorkerInterface_Expecter{mock: &_m.Mock}
}

// DlqWorker provides a mock function for the type MockWorkerInterface
func (_mock *MockWorkerInterface) DlqWorker(task *domain.SagaTask, sess database.Session) error {
	ret := _mock.Called(task, sess)

	if len(ret) == 0 {
		panic("no return value specified for DlqWorker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.SagaTask, database.Session) error); ok {
		r0 = returnFunc(task, sess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkerInterface_DlqWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DlqWorker'
type MockWorkerInterface_DlqWorker_Call struct {
	*mock.Call
}

// DlqWorker is a helper method to define mock.On call
//   - task *domain.SagaTask
//   - sess database.Session
func (_e *MockWorkerInterface_Expecter) DlqWorker(task interface{}, sess interface{}) *MockWorkerInterface_DlqWorker_Call {
	return &MockWorkerInterface_DlqWorker_Call{Call: _e.mock.On("DlqWorker", task, sess)}
}

func (_c *MockWorkerInterface_DlqWorker_Call) Run(run func(task *domain.SagaTask, sess database.Session)) *MockWorkerInterface_DlqWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.SagaTask
		if args[0] != nil {
			arg0 = args[0].(*domain.SagaTask)
		}
		var arg1 database.Session
		if args[1] != nil {
			arg1 = args[1].(database.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkerInterface_DlqWorker_Call) Return(err error) *MockWorkerInterface_DlqWorker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkerInterface_DlqWorker_Call) RunAndReturn(run func(task *domain.SagaTask, sess database.Session) error) *MockWorkerInterface_DlqWorker_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type MockWorkerInterface
func (_mock *MockWorkerInterface) New(ctx context.Context) (gosaga.WorkerInterface, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 gosaga.WorkerInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (gosaga.WorkerInterface, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) gosaga.WorkerInterface); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gosaga.WorkerInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkerInterface_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockWorkerInterface_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWorkerInterface_Expecter) New(ctx interface{}) *MockWorkerInterface_New_Call {
	return &MockWorkerInterface_New_Call{Call: _e.mock.On("New", ctx)}
}

func (_c *MockWorkerInterface_New_Call) Run(run func(ctx context.Context)) *MockWorkerInterface_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkerInterface_New_Call) Return(workerInterface gosaga.WorkerInterface, err error) *MockWorkerInterface_New_Call {
	_c.Call.Return(workerInterface, err)
	return _c
}

func (_c *MockWorkerInterface_New_Call) RunAndReturn(run func(ctx context.Context) (gosaga.WorkerInterface, error)) *MockWorkerInterface_New_Call {
	_c.Call.Return(run)
	return _c
}

// Worker provides a mock function for the type MockWorkerInterface
func (_mock *MockWorkerInterface) Worker(task *domain.SagaTask, sess database.Session) error {
	ret := _mock.Called(task, sess)

	if len(ret) == 0 {
		panic("no return value specified for Worker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.SagaTask, database.Session) error); ok {
		r0 = returnFunc(task, sess)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkerInterface_Worker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Worker'
type MockWorkerInterface_Worker_Call struct {
	*mock.Call
}

// Worker is a helper method to define mock.On call
//   - task *domain.SagaTask
//   - sess database.Session
func (_e *MockWorkerInterface_Expecter) Worker(task interface{}, sess interface{}) *MockWorkerInterface_Worker_Call {
	return &MockWorkerInterface_Worker_Call{Call: _e.mock.On("Worker", task, sess)}
}

func (_c *MockWorkerInterface_Worker_Call) Run(run func(task *domain.SagaTask, sess database.Session)) *MockWorkerInterface_Worker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.SagaTask
		if args[0] != nil {
			arg0 = args[0].(*domain.SagaTask)
		}
		var arg1 database.Session
		if args[1] != nil {
			arg1 = args[1].(database.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkerInterface_Worker_Call) Return(err error) *MockWorkerInterface_Worker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkerInterface_Worker_Call) RunAndReturn(run func(task *domain.SagaTask, sess database.Session) error) *MockWorkerInterface_Worker_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktxBeginner creates a new instance of mocktxBeginner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktxBeginner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktxBeginner {
	mock := &mocktxBeginner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktxBeginner is an autogenerated mock type for the txBeginner type
type mocktxBeginner struct {
	mock.Mock
}

type mocktxBeginner_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktxBeginner) EXPECT() *mocktxBeginner_Expecter {
	return &mocktxBeginner_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type mocktxBeginner
func (_mock *mocktxBeginner) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktxBeginner_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type mocktxBeginner_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *mocktxBeginner_Expecter) BeginTx(ctx interface{}, txOptions interface{}) *mocktxBeginner_BeginTx_Call {
	return &mocktxBeginner_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *mocktxBeginner_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *mocktxBeginner_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktxBeginner_BeginTx_Call) Return(tx pgx.Tx, err error) *mocktxBeginner_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *mocktxBeginner_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *mocktxBeginner_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}
