// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"context"

	"github.com/Filin153/gosaga/domain"
	"github.com/Filin153/gosaga/storage/database"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Create(task *domain.SagaTask) (int64, error) {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.SagaTask) (int64, error)); ok {
		return returnFunc(task)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.SagaTask) int64); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.SagaTask) error); ok {
		r1 = returnFunc(task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - task *domain.SagaTask
func (_e *MockTaskRepository_Expecter) Create(task interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", task)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(task *domain.SagaTask)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.SagaTask
		if args[0] != nil {
			arg0 = args[0].(*domain.SagaTask)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(n int64, err error) *MockTaskRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(task *domain.SagaTask) (int64, error)) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Delete(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockTaskRepository_Expecter) Delete(id interface{}) *MockTaskRepository_Delete_Call {
	return &MockTaskRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTaskRepository_Delete_Call) Run(run func(id int64)) *MockTaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Delete_Call) Return(err error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Delete_Call) RunAndReturn(run func(id int64) error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByID(id int64) (*domain.SagaTask, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.SagaTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*domain.SagaTask, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *domain.SagaTask); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SagaTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockTaskRepository_Expecter) GetByID(id interface{}) *MockTaskRepository_GetByID_Call {
	return &MockTaskRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockTaskRepository_GetByID_Call) Run(run func(id int64)) *MockTaskRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) Return(sagaTask *domain.SagaTask, err error) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(sagaTask, err)
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) RunAndReturn(run func(id int64) (*domain.SagaTask, error)) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdempotencyKey provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByIdempotencyKey(key string) (*domain.SagaTask, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 *domain.SagaTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.SagaTask, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.SagaTask); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SagaTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdempotencyKey'
type MockTaskRepository_GetByIdempotencyKey_Call struct {
	*mock.Call
}

// GetByIdempotencyKey is a helper method to define mock.On call
//   - key string
func (_e *MockTaskRepository_Expecter) GetByIdempotencyKey(key interface{}) *MockTaskRepository_GetByIdempotencyKey_Call {
	return &MockTaskRepository_GetByIdempotencyKey_Call{Call: _e.mock.On("GetByIdempotencyKey", key)}
}

func (_c *MockTaskRepository_GetByIdempotencyKey_Call) Run(run func(key string)) *MockTaskRepository_GetByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetByIdempotencyKey_Call) Return(sagaTask *domain.SagaTask, err error) *MockTaskRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(sagaTask, err)
	return _c
}

func (_c *MockTaskRepository_GetByIdempotencyKey_Call) RunAndReturn(run func(key string) (*domain.SagaTask, error)) *MockTaskRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStatus provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByStatus(status domain.TaskStatus) ([]domain.SagaTask, error) {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatus")
	}

	var r0 []domain.SagaTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.TaskStatus) ([]domain.SagaTask, error)); ok {
		return returnFunc(status)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.TaskStatus) []domain.SagaTask); ok {
		r0 = returnFunc(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SagaTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.TaskStatus) error); ok {
		r1 = returnFunc(status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStatus'
type MockTaskRepository_GetByStatus_Call struct {
	*mock.Call
}

// GetByStatus is a helper method to define mock.On call
//   - status domain.TaskStatus
func (_e *MockTaskRepository_Expecter) GetByStatus(status interface{}) *MockTaskRepository_GetByStatus_Call {
	return &MockTaskRepository_GetByStatus_Call{Call: _e.mock.On("GetByStatus", status)}
}

func (_c *MockTaskRepository_GetByStatus_Call) Run(run func(status domain.TaskStatus)) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.TaskStatus
		if args[0] != nil {
			arg0 = args[0].(domain.TaskStatus)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetByStatus_Call) Return(sagaTasks []domain.SagaTask, err error) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Return(sagaTasks, err)
	return _c
}

func (_c *MockTaskRepository_GetByStatus_Call) RunAndReturn(run func(status domain.TaskStatus) ([]domain.SagaTask, error)) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Update(task *domain.SagaTask) error {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.SagaTask) error); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - task *domain.SagaTask
func (_e *MockTaskRepository_Expecter) Update(task interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", task)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(task *domain.SagaTask)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.SagaTask
		if args[0] != nil {
			arg0 = args[0].(*domain.SagaTask)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(err error) *MockTaskRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(task *domain.SagaTask) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) UpdateByID(id int64, update domain.SagaTaskUpdate) error {
	ret := _mock.Called(id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, domain.SagaTaskUpdate) error); ok {
		r0 = returnFunc(id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockTaskRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - id int64
//   - update domain.SagaTaskUpdate
func (_e *MockTaskRepository_Expecter) UpdateByID(id interface{}, update interface{}) *MockTaskRepository_UpdateByID_Call {
	return &MockTaskRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", id, update)}
}

func (_c *MockTaskRepository_UpdateByID_Call) Run(run func(id int64, update domain.SagaTaskUpdate)) *MockTaskRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 domain.SagaTaskUpdate
		if args[1] != nil {
			arg1 = args[1].(domain.SagaTaskUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_UpdateByID_Call) Return(err error) *MockTaskRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_UpdateByID_Call) RunAndReturn(run func(id int64, update domain.SagaTaskUpdate) error) *MockTaskRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// WithSession provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) WithSession(sess database.Session) database.TaskRepository {
	ret := _mock.Called(sess)

	if len(ret) == 0 {
		panic("no return value specified for WithSession")
	}

	var r0 database.TaskRepository
	if returnFunc, ok := ret.Get(0).(func(database.Session) database.TaskRepository); ok {
		r0 = returnFunc(sess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.TaskRepository)
		}
	}
	return r0
}

// MockTaskRepository_WithSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithSession'
type MockTaskRepository_WithSession_Call struct {
	*mock.Call
}

// WithSession is a helper method to define mock.On call
//   - sess database.Session
func (_e *MockTaskRepository_Expecter) WithSession(sess interface{}) *MockTaskRepository_WithSession_Call {
	return &MockTaskRepository_WithSession_Call{Call: _e.mock.On("WithSession", sess)}
}

func (_c *MockTaskRepository_WithSession_Call) Run(run func(sess database.Session)) *MockTaskRepository_WithSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Session
		if args[0] != nil {
			arg0 = args[0].(database.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_WithSession_Call) Return(taskRepository database.TaskRepository) *MockTaskRepository_WithSession_Call {
	_c.Call.Return(taskRepository)
	return _c
}

func (_c *MockTaskRepository_WithSession_Call) RunAndReturn(run func(sess database.Session) database.TaskRepository) *MockTaskRepository_WithSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDLQRepository creates a new instance of MockDLQRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDLQRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDLQRepository {
	mock := &MockDLQRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDLQRepository is an autogenerated mock type for the DLQRepository type
type MockDLQRepository struct {
	mock.Mock
}

type MockDLQRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDLQRepository) EXPECT() *MockDLQRepository_Expecter {
	return &MockDLQRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) Create(task *domain.DLQTask) (int64, error) {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.DLQTask) (int64, error)); ok {
		return returnFunc(task)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.DLQTask) int64); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.DLQTask) error); ok {
		r1 = returnFunc(task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDLQRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - task *domain.DLQTask
func (_e *MockDLQRepository_Expecter) Create(task interface{}) *MockDLQRepository_Create_Call {
	return &MockDLQRepository_Create_Call{Call: _e.mock.On("Create", task)}
}

func (_c *MockDLQRepository_Create_Call) Run(run func(task *domain.DLQTask)) *MockDLQRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.DLQTask
		if args[0] != nil {
			arg0 = args[0].(*domain.DLQTask)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_Create_Call) Return(n int64, err error) *MockDLQRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDLQRepository_Create_Call) RunAndReturn(run func(task *domain.DLQTask) (int64, error)) *MockDLQRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) Delete(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDLQRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDLQRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockDLQRepository_Expecter) Delete(id interface{}) *MockDLQRepository_Delete_Call {
	return &MockDLQRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockDLQRepository_Delete_Call) Run(run func(id int64)) *MockDLQRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_Delete_Call) Return(err error) *MockDLQRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDLQRepository_Delete_Call) RunAndReturn(run func(id int64) error) *MockDLQRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) GetByID(id int64) (*domain.DLQTask, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.DLQTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*domain.DLQTask, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *domain.DLQTask); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DLQTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDLQRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockDLQRepository_Expecter) GetByID(id interface{}) *MockDLQRepository_GetByID_Call {
	return &MockDLQRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockDLQRepository_GetByID_Call) Run(run func(id int64)) *MockDLQRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_GetByID_Call) Return(dLQTask *domain.DLQTask, err error) *MockDLQRepository_GetByID_Call {
	_c.Call.Return(dLQTask, err)
	return _c
}

func (_c *MockDLQRepository_GetByID_Call) RunAndReturn(run func(id int64) (*domain.DLQTask, error)) *MockDLQRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStatus provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) GetByStatus(status domain.TaskStatus) ([]domain.DLQEntry, error) {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatus")
	}

	var r0 []domain.DLQEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.TaskStatus) ([]domain.DLQEntry, error)); ok {
		return returnFunc(status)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.TaskStatus) []domain.DLQEntry); ok {
		r0 = returnFunc(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DLQEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.TaskStatus) error); ok {
		r1 = returnFunc(status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_GetByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStatus'
type MockDLQRepository_GetByStatus_Call struct {
	*mock.Call
}

// GetByStatus is a helper method to define mock.On call
//   - status domain.TaskStatus
func (_e *MockDLQRepository_Expecter) GetByStatus(status interface{}) *MockDLQRepository_GetByStatus_Call {
	return &MockDLQRepository_GetByStatus_Call{Call: _e.mock.On("GetByStatus", status)}
}

func (_c *MockDLQRepository_GetByStatus_Call) Run(run func(status domain.TaskStatus)) *MockDLQRepository_GetByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.TaskStatus
		if args[0] != nil {
			arg0 = args[0].(domain.TaskStatus)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_GetByStatus_Call) Return(dLQEntrys []domain.DLQEntry, err error) *MockDLQRepository_GetByStatus_Call {
	_c.Call.Return(dLQEntrys, err)
	return _c
}

func (_c *MockDLQRepository_GetByStatus_Call) RunAndReturn(run func(status domain.TaskStatus) ([]domain.DLQEntry, error)) *MockDLQRepository_GetByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTaskID provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) GetByTaskID(taskID int64) (*domain.DLQTask, error) {
	ret := _mock.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTaskID")
	}

	var r0 *domain.DLQTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*domain.DLQTask, error)); ok {
		return returnFunc(taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *domain.DLQTask); ok {
		r0 = returnFunc(taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DLQTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_GetByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTaskID'
type MockDLQRepository_GetByTaskID_Call struct {
	*mock.Call
}

// GetByTaskID is a helper method to define mock.On call
//   - taskID int64
func (_e *MockDLQRepository_Expecter) GetByTaskID(taskID interface{}) *MockDLQRepository_GetByTaskID_Call {
	return &MockDLQRepository_GetByTaskID_Call{Call: _e.mock.On("GetByTaskID", taskID)}
}

func (_c *MockDLQRepository_GetByTaskID_Call) Run(run func(taskID int64)) *MockDLQRepository_GetByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_GetByTaskID_Call) Return(dLQTask *domain.DLQTask, err error) *MockDLQRepository_GetByTaskID_Call {
	_c.Call.Return(dLQTask, err)
	return _c
}

func (_c *MockDLQRepository_GetByTaskID_Call) RunAndReturn(run func(taskID int64) (*domain.DLQTask, error)) *MockDLQRepository_GetByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// GetErrorsWithAttempts provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) GetErrorsWithAttempts() ([]domain.DLQEntry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetErrorsWithAttempts")
	}

	var r0 []domain.DLQEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.DLQEntry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.DLQEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DLQEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQRepository_GetErrorsWithAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetErrorsWithAttempts'
type MockDLQRepository_GetErrorsWithAttempts_Call struct {
	*mock.Call
}

// GetErrorsWithAttempts is a helper method to define mock.On call
func (_e *MockDLQRepository_Expecter) GetErrorsWithAttempts() *MockDLQRepository_GetErrorsWithAttempts_Call {
	return &MockDLQRepository_GetErrorsWithAttempts_Call{Call: _e.mock.On("GetErrorsWithAttempts")}
}

func (_c *MockDLQRepository_GetErrorsWithAttempts_Call) Run(run func()) *MockDLQRepository_GetErrorsWithAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDLQRepository_GetErrorsWithAttempts_Call) Return(dLQEntrys []domain.DLQEntry, err error) *MockDLQRepository_GetErrorsWithAttempts_Call {
	_c.Call.Return(dLQEntrys, err)
	return _c
}

func (_c *MockDLQRepository_GetErrorsWithAttempts_Call) RunAndReturn(run func() ([]domain.DLQEntry, error)) *MockDLQRepository_GetErrorsWithAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) Update(task *domain.DLQTask) error {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.DLQTask) error); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDLQRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDLQRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - task *domain.DLQTask
func (_e *MockDLQRepository_Expecter) Update(task interface{}) *MockDLQRepository_Update_Call {
	return &MockDLQRepository_Update_Call{Call: _e.mock.On("Update", task)}
}

func (_c *MockDLQRepository_Update_Call) Run(run func(task *domain.DLQTask)) *MockDLQRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.DLQTask
		if args[0] != nil {
			arg0 = args[0].(*domain.DLQTask)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_Update_Call) Return(err error) *MockDLQRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDLQRepository_Update_Call) RunAndReturn(run func(task *domain.DLQTask) error) *MockDLQRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) UpdateByID(id int64, update domain.DLQTaskUpdate) error {
	ret := _mock.Called(id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, domain.DLQTaskUpdate) error); ok {
		r0 = returnFunc(id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDLQRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockDLQRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - id int64
//   - update domain.DLQTaskUpdate
func (_e *MockDLQRepository_Expecter) UpdateByID(id interface{}, update interface{}) *MockDLQRepository_UpdateByID_Call {
	return &MockDLQRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", id, update)}
}

func (_c *MockDLQRepository_UpdateByID_Call) Run(run func(id int64, update domain.DLQTaskUpdate)) *MockDLQRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 domain.DLQTaskUpdate
		if args[1] != nil {
			arg1 = args[1].(domain.DLQTaskUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDLQRepository_UpdateByID_Call) Return(err error) *MockDLQRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDLQRepository_UpdateByID_Call) RunAndReturn(run func(id int64, update domain.DLQTaskUpdate) error) *MockDLQRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// WithSession provides a mock function for the type MockDLQRepository
func (_mock *MockDLQRepository) WithSession(sess database.Session) database.DLQRepository {
	ret := _mock.Called(sess)

	if len(ret) == 0 {
		panic("no return value specified for WithSession")
	}

	var r0 database.DLQRepository
	if returnFunc, ok := ret.Get(0).(func(database.Session) database.DLQRepository); ok {
		r0 = returnFunc(sess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.DLQRepository)
		}
	}
	return r0
}

// MockDLQRepository_WithSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithSession'
type MockDLQRepository_WithSession_Call struct {
	*mock.Call
}

// WithSession is a helper method to define mock.On call
//   - sess database.Session
func (_e *MockDLQRepository_Expecter) WithSession(sess interface{}) *MockDLQRepository_WithSession_Call {
	return &MockDLQRepository_WithSession_Call{Call: _e.mock.On("WithSession", sess)}
}

func (_c *MockDLQRepository_WithSession_Call) Run(run func(sess database.Session)) *MockDLQRepository_WithSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.Session
		if args[0] != nil {
			arg0 = args[0].(database.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDLQRepository_WithSession_Call) Return(dLQRepository database.DLQRepository) *MockDLQRepository_WithSession_Call {
	_c.Call.Return(dLQRepository)
	return _c
}

func (_c *MockDLQRepository_WithSession_Call) RunAndReturn(run func(sess database.Session) database.DLQRepository) *MockDLQRepository_WithSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSession creates a new instance of MockSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSession {
	mock := &MockSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSession is an autogenerated mock type for the Session type
type MockSession struct {
	mock.Mock
}

type MockSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSession) EXPECT() *MockSession_Expecter {
	return &MockSession_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockSession
func (_mock *MockSession) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(arguments) > 0 {
		tmpRet = _mock.Called(ctx, sql, arguments)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, arguments...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSession_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...any
func (_e *MockSession_Expecter) Exec(ctx interface{}, sql interface{}, arguments ...interface{}) *MockSession_Exec_Call {
	return &MockSession_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, arguments...)...)}
}

func (_c *MockSession_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...any)) *MockSession_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSession_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockSession_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockSession_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)) *MockSession_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockSession
func (_mock *MockSession) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockSession_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockSession_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *MockSession_Query_Call {
	return &MockSession_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockSession_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockSession_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSession_Query_Call) Return(rows pgx.Rows, err error) *MockSession_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockSession_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgx.Rows, error)) *MockSession_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockSession
func (_mock *MockSession) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// MockSession_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockSession_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockSession_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *MockSession_QueryRow_Call {
	return &MockSession_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockSession_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockSession_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSession_QueryRow_Call) Return(row pgx.Row) *MockSession_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockSession_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) pgx.Row) *MockSession_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
